# Site settings
title: idiazroncero
email: idiaz.roncero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Un blog absolutamente desnortado en el que un día se habla de CSS3
  y al siguiente de política iraní.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: idiazroncero
github_username:  idiazroncero
sass_dir: _compass
# Build settings
markdown: kramdown
# compresion de html
compress_html:
  clippings: [a, div]
# Syntax highlighter
highlighter: pygments